name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: simplesite-bucket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: ./main

  readme-to-pdf:
    runs-on: pandoc/latex
    steps:
      - run: pandoc ./README.md -s -o ./README.pdf
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: readme.pdf
          path: ./README.pdf
