name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: simplesite-bucket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: ./main

  readme-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt update && sudo apt install pandoc

      - name: Convert README.md to PDF
        uses: docker://pandoc/latex:latest  # Use 'pandoc/core' for simpler conversions
        with:
          args: --from markdown --to pdf README.md -o README.pdf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: README.pdf
          path: README.pdf
